catalog/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.VideoUploadView.as_view(), name='index'),
    path('videos/<str:folder_name>/<str:video_action>', views.VideoListView.as_view(), name='videos'),
    # parameter at video detail <str:video_title>, it WORKS EVEN for invalid video string title
    # video_title parameter can be invoked in corresponding VIEW later then 
    path('video/<str:folder_name>/<str:video_type>/<str:video_title>', views.VideoDetailView.as_view(), name='video-detail'),
    path('video-upload', views.VideoUploadView.as_view(), name='video-upload'),
    path('delete-videos', views.DeleteVideoView.as_view(), name='delete-videos'),
    path('progress', views.progress_view, name='progress'),
]

locallibrary/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    # path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    # path('celery-progress/', include('celery_progress.urls', namespace='celery_progress')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from __future__ import unicode_literals

from django.db import models

class Video(models.Model):
    row_id = models.IntegerField(null=False,blank=True,primary_key=True)
    status = models.CharField(max_length=255, blank=True) 
    title = models.CharField(max_length=255, blank=True)
    filesize = models.CharField(max_length=10, blank=True)
    file = models.FileField(upload_to='videos/upload/')
    file_score32 = models.FileField(upload_to='features/', default="")
    file_score64 = models.FileField(upload_to='features/', default="")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    task_id = models.CharField(max_length=50, default='')

    def __str__(self):
        str_row_id = str(self.row_id)
        return str_row_id

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Traffic Abnormal Detection{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		
		{% comment %} CSS for video_list.html {% endcomment %}
  </head>
  <body>
		{% include 'includes/header.html' %}
		
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
    
		{% include 'includes/footer.html' %}
		
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/home.html
<!-- {% extends 'base.html' %}
{% endblock %} -->