catalog/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.VideoUploadView.as_view(), name='index'),
    path('videos/<str:folder_name>/<str:video_action>', views.VideoListView.as_view(), name='videos'),
    # parameter at video detail <str:video_title>, it WORKS EVEN for invalid video string title
    # video_title parameter can be invoked in corresponding VIEW later then 
    path('video/<str:folder_name>/<str:video_type>/<str:video_title>', views.VideoDetailView.as_view(), name='video-detail'),
    path('video-upload', views.VideoUploadView.as_view(), name='video-upload'),
    path('delete-videos', views.DeleteVideoView.as_view(), name='delete-videos'),
    path('progress', views.progress_view, name='progress'),
]

locallibrary/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    # path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    # path('celery-progress/', include('celery_progress.urls', namespace='celery_progress')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from __future__ import unicode_literals

from django.db import models

class Video(models.Model):
    row_id = models.IntegerField(null=False,blank=True,primary_key=True)
    status = models.CharField(max_length=255, blank=True) 
    title = models.CharField(max_length=255, blank=True)
    filesize = models.CharField(max_length=10, blank=True)
    file = models.FileField(upload_to='videos/upload/')
    file_score32 = models.FileField(upload_to='features/', default="")
    file_score64 = models.FileField(upload_to='features/', default="")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    task_id = models.CharField(max_length=50, default='')

    def __str__(self):
        str_row_id = str(self.row_id)
        return str_row_id

catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.

from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('file', )

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core.files.storage import FileSystemStorage
from django.views import View
from django.conf import settings
from django.core import files
from django.utils.text import slugify
import time
# A view function, or view for short, 
# is simply a Python function that takes a Web request and returns a Web response. 
# This response can be the HTML contents of a Web page, or a redirect, or a 404 error,
# or an XML document, or an image . . . or anything, really.
from django.views import generic
from .models import Video
from .forms import VideoForm
from .tasks import extract_feature, my_task

import os
import json
import glob
import urllib.request
import tempfile
from pytube import YouTube

from fe_c3d.extract_feature import load_npy, extract_feature_video
from fe_c3d.configuration import weight_default_path, weight32_path, weight64_path
from catalog.utils.utils import load_annotation, format_filesize, url_downloadable, write_file, get_basename

def index(request):
    """View function for home page of site."""

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable.
    print(request.path)
    
    return render(
        request,
        'index.html',
        context={
            'num_visits': num_visits,
            }
    )

class VideoListView(generic.TemplateView):
    template_name = 'catalog/video_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        action = context['video_action']
        print("action: ",action)
        folder_name = context['folder_name']
        # print("folder_name: ",folder_name)
        # print("path: ","/media/output/"+folder_name+"/"+action+"/*.png")
        gifs = sorted(glob.glob("media/output/"+folder_name+"/"+action+"/*.png"))
        # gifs = sorted(glob.glob('media/gifs/{}/*.gif'.format(action)))
        # print("gifs: ",gifs)
        for i, value in enumerate(gifs):
            value = "/"+value
            title = value.split("/")[-1].split(".")[0]#os.path.basename(value)[:-4]
            # print("path: {},\ntitle: {}".format(value,title))
            video = {'url': '/catalog/video/{}/{}/'.format(folder_name,action) + title,'basename': title, 'title': title,'src':value,"action":action}
            gifs[i] = video

        # update context
        context['gifs'] = gifs
        context['action'] = action
        return context
        
class VideoDetailView(generic.TemplateView):
    template_name = 'catalog/video_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        folder_name = context['folder_name']
        action = context['video_type']
        title = context['video_title'] # title from URL

        video_path = '/media/output/{}/{}/{}.mp4'.format(folder_name,action, title)
        context['video'] = {'url': '/media/output/{}/{}/{}.mp4'.format(folder_name,action, title), 'title': title, 'video_path': video_path}
        context["vid_det"] = {'video_id':title,"action":action,'location':"Hyderabad","incident_time":"time"}
        return context        

class VideoUploadView(View):
    def get(self, request):
        # Order by descent of uploaded time
        videos_list = Video.objects.order_by('-uploaded_at')
        print(">>>>>>>>>>>>>>>>> In Get <<<<<<<<<<<<<<")
        print("videos_list: ",videos_list)
        return render(self.request, 'catalog/video_upload.html', {'videos': videos_list})

    def post(self, request):
        """
        Post from form blue-upload or url.
        """
        #time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
        url = request.POST.get('url')
        filename = request.POST.get('filename')

        response = {'is_valid': False}

        form = VideoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            print(">>> In form")
            video = form.save()
            video.filesize = format_filesize(video.file.size)
            video.title = get_basename(video.file.name)
            video.row_id = video.__class__.objects.count()
            video.save()

            print(f"row_id:{video.row_id}, name: {video.file.name}, url: {video.file.url}, filesize: {video.filesize},title: {video.title}, status: {video.status}")
            # response = {'is_valid': True, 'name': video.file.name, 'url': video.file.url, 'id': video.id, 'filesize': video.filesize, 'title': video.title}
            response = {'is_valid': True, 'row_id':video.row_id,'name': video.file.name, 'url': video.file.url, 'filesize': video.filesize, 'title': video.title,'status':video.status}
        elif url:
            print("In URL")
            url_response = urllib.request.urlopen(url)
            url_info = url_response.info()
            
            if 'video' in url_info.get_content_type():
                print("In Video")
                temp_video = tempfile.NamedTemporaryFile()
                write_file(temp_video, url_response)

                video = Video()
                objects_count = video.objects.count()
                print("Video Table Objects Count: ",objects_count)
                video.file.save(filename, files.File(temp_video))
                video.filesize = format_filesize(video.file.size)
                video.title = get_basename(video.file.name)
                video.save()
                response = {'is_valid': True, 'name': video.file.name, 'url': video.file.url, 'filesize': video.filesize, 'title': video.title,'status':video.status}

        # Extract Feature in Celery
        if response['is_valid'] == True:
            # video = Video()
            # print(video.id)
            # video_id = video.row_id+1
            task = extract_feature(response["row_id"])
            # assert(False)
            video.status = "registered"
            # video.task_id = task.task_id
            video.save()
            # response['task_id'] = task.task_id

        return JsonResponse(response)

class DeleteVideoView(View):
    def post(self, request):
        response = {'success': False}
        print(request.POST)
        if request.POST.get('delete_all'):
            videos = Video.objects.all()
            for video in videos:
                video.file.delete()
                video.file_score32.delete()
                video.file_score64.delete()
                video.delete()
            videos.delete()
            response = {'success': True}
        else:
            # file_names = request.POST.getlist('files[]')
            ids = request.POST.getlist('ids[]')
            for id in ids:
                video = Video.objects.get(id = id)
                video.file.delete()
                video.file_score32.delete()
                video.file_score64.delete()
                video.delete()
            response = {'success': True}
            
        return JsonResponse(response)

from celery.result import AsyncResult
from .tasks import add 
def progress_view(request):
    result = my_task.delay(100)
    return render(request, 'catalog/progress.html', context={'task_id': result.task_id})

catalog/templates/catalog/video_detail.html
{% extends "base_generic.html" %}

{% load static %}
{% comment %} use the files in the static folder in this template. {% endcomment %}

{% block title %}Video {{ video.title }}{% endblock %}

{% block videos_content %}

<div class='container'>


    <div class="row">
        <div class='col-md-12'>
            <div class='panel panel-default'>
            </div>
        </div>

    </div>

    <div class='col-sm-5 border-right text-center'>
        <video controls id='video-player' width="100%" height="320" onended="FunctionEnded()" onpause="FunctionPause()" onplay="FunctionPlay()">
            <source src="{{ video.url }}" type="video/mp4">
        </video>
    </div>
    <div class='col-sm-7' style="display: relative">
        
    <div class="d-flex th-wraper">
        <div class="th-list">
            <h4>Video ID: <span id="video_id" style="color: blueviolet;background-color: white;" class="label label-default">{{ vid_det.video_id }}</span></h4>
            <h4>Action: <span id="action" style="color: blueviolet;background-color: white;" class="label label-default">{{ vid_det.action }}</span></h4>
            <h4>Location: <span id="location" style="color: blueviolet;background-color: white;" class="label label-default">{{ vid_det.location }}</span></h4>
            <h4>Incident Time: <span id="incd_time" style="color: blueviolet;background-color: white;" class="label label-default">{{ vid_det.incident_time }}</span></h4>
        </div>
    </div>
    </div>

   
</div>


{% endblock %}

{% block javascript %}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="{% static 'js/VideoFrame.min.js' %}"></script>
<script src="{% static 'js/video_interactive.js' %}"></script>
<script>
function FunctionPlay(){
    $("#play-pause").html('<img src="https://iconsplace.com/wp-content/uploads/_icons/ffffff/256/png/pause-icon-18-256.png" style="height:23px;margin-bottom:2px"/> Pause');
}    
function FunctionPause(){
    $("#play-pause").html('<img src="https://iconsplace.com/wp-content/uploads/_icons/ffffff/256/png/play-icon-18-256.png" style="height:23px;margin-bottom:2px"/> Play');
}
function FunctionEnded(){
    $("#play-pause").html('<img src="https://iconsplace.com/wp-content/uploads/_icons/ffffff/256/png/play-icon-18-256.png" style="height:23px;margin-bottom:2px"/> Play');
}
</script>
{% endblock %}

catalog/templates/catalog/video_list.html
{% extends "base_generic.html" %}

{% block title %}Videos List{% endblock %}

{% load static %} 
{% block videos_content %}
  <div class="container">

    <ul class="nav nav-tabs nav-video-list">
      <li role="presentation" class="{% if action == 'abnormal' %} active {% endif %}"><a href="{{video.path_abnormal}}">Abnormal Videos</a></li>
      <li role="presentation" class="{% if action == 'normal' %} active {% endif %}"><a href="{{video.path_normal}}">Normal Videos</a></li>
      <!-- <li role="presentation"><a href="#">Orther</a></li> -->
    </ul>
    <div class='video-list' style="padding-top: 15px">
      {% if gifs %}
        {% for video in gifs %}

        <div class="col-lg-3 col-md-4 col-sm-6">
          <a href="{{ video.url }}" class = "thumbnail">
            <img src="{{ video.src }}" style="padding: 5px" alt={{video.title}}>
            <p class="text-center">{{ video.title }}</p>
          </a>
        </div>
        {% endfor %}

      {% else %}
        <p>There are no videos in the server.</p>
      {% endif %}
    </div>

  </div>
{% endblock %}

{% block javascript %}
  <!-- <script type="text/javascript">
    $(function(){
      $('.nav-video-list>li>a').click(function() {
        let video_action = $('li:active').attr('data-action');
        $.ajax({
          type: 'GET',
          url: '/catalog/get-videos',
          data: {
            video_action,
          },
          success: function(data) {
            let video_list = data.result;
            let html = '';
            for(video in video_list){
              html.append(`
              <div class="col-lg-3 col-md-4 col-sm-6">
                <a href="${ video.url }" class = "thumbnail">
                  <img src="/media/gifs/abnormal/${ video.title }.gif" alt='${video.title}'>
                  ${ video.title }
                </a>
              </div>`);
            }
            $('video-list').innerHTML = html;
          }
        });
      })
    })
  </script> -->

{% endblock %}

catalog/templates/catalog/video_upload.html
{% extends "base_generic.html" %}


{% load static %}

{% block title %}Traffic Anomaly{% endblock %}

{% block videos_content %}
<div class="container">
  <div class="well text-muted text-center" style="padding-top: 1rem; padding-bottom: 1rem;">
    <span class="glyphicon glyphicon-arrow-down" style="font-size: 2rem;"></span>
    <h4>Upload Your Video Here</h4>
  </div>
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-videos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload
    </button>
    <!-- <button type="reset" class="btn btn-warning cancel">
      <span class="glyphicon glyphicon-ban-circle"></span>Cancel Upload
    </button> -->
    <button type="submit" class="btn btn-danger js-delete-all-video">
      <span class="glyphicon glyphicon-trash"></span> Delete All
    </button>
    
    <!-- <button type="button" class="btn btn-primary js-extract-feature">
      <span class="glyphicon glyphicon-cloud-upload"></span> Extract Feature
    </button>   -->
    <input id="fileupload" type="file" name="file" multiple accept="video/*,image/gif" style="display: none;"
      data-url="{% url 'catalog:video-upload' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <table id="gallery" class="table table-striped">
    <thead>
      <tr>
        <th>Videos</th>
        <th>Size</th>
        <!-- <th>Status</th> -->
      </tr>
    </thead>
    <tbody>
      {% csrf_token %}
      {% for video in videos %}
      <tr>
        <td>
          <a class='btn' href="/catalog/videos/{{video.title}}/abnormal" style="padding: 0">{{ video.title }}</a>
        </td>
        <td>
          <span>{{ video.filesize }}</span>
        </td>
        <!-- <td>
          <span>{{ video.status }}</span>
        </td> -->
        <td style="max-width: 147px">
        </td>
        <td>
          <button type="submit" class="btn btn-danger js-delete-videos pull-right" data-type='DELETE' data-url="{{video.file}}" data-id='{{video.id}}'>
            <span class="glyphicon glyphicon-trash"></span> Delete
          </button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Back</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="model-urls" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <!-- <span class="glyphicon glyphicon-link"></span> -->
            <img src="{% static 'images/yt_logo_rgb_light.png'%}" style="height: 17px; margin-left: 10px;">
            <h4 style="text-align: center">Upload with URLs</h4>
          </h5>
        </div>
        <div class="modal-body">
            <div class="form-group">
              <input type="url" class="form-control form-check-input left-inner-addon input-url" placeholder="url media or youtube..." aria-describedby="basic-addon1" required>
              <div class="help-block with-errors" style="display: none;color: red;">URL Invalid</div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control form-check-input left-inner-addon input-filename" placeholder="filename..." aria-describedby="basic-addon1">
            </div>
        </div>
        <div class="modal-footer">
          <i class="fa fa-spinner fa-spin processing" style="display: none"></i>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary js-url-upload">
            <span class="glyphicon glyphicon-cloud-upload"></span> Upload
          </button>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

{% block javascript %}
{# JQUERY FILE UPLOAD SCRIPTS #}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

<script src="{% static 'js/celery_progress.js' %}"></script>

{# VIDEO PAGE SCRIPTS #}
<script src="{% static 'js/upload.js' %}"></script>
{% endblock %}